export const strings = {
  "account.info": "Account Info",
  "account.assigned.products": "Account Assigned Products",
  "common.home": "Home",
  "common.edit": "Edit",
  "common.cancel": "Cancel",
  "common.save": "Save",
  "common.delete": "Delete",
  "common.confirm.delete": "Confirm Delete",
  "common.delete.user": "Delete User",
  "common.error": "Error",
  "common.login": "Log In",
  "common.logout": "Log Out",
  "common.add": "Add",
  "common.remove": "Remove",
  "assigned.classes": "Assigned Classes",
  "dashboard.title": "Crew Progress Dashboard",
  "please.login": "Please Login to continue",
  "nav.more": "More",
  "nav.admin": "Admin",
  "nav.safety": "Safety",
  "nav.troubleshooting": "Troubleshooting",
  "nav.mob.inspection.checklist": "MOB Inspection Checklist",
  "nav.mob.drill.log": "MOB Drill Log",
  "nav.certification": "Certification",
  "only.change.needed":
    "Only change what is needed, rest of the values will remain.",
  "info.missing": "info missing",
  "select.user.editing": "Please select a user to begin editing",
  "serial.number.section.header": "Product Serial Numbers",
  "serial.number.table.header": "Serial Number",
  "serial.number.actions": "Actions",
};
