export const strings = {
  "account.info": "Account Info",
  "account.assigned.products": "Account Assigned Products",
  "common.home": "Home",
  "common.edit": "Edit",
  "common.cancel": "Cancel",
  "common.save": "Save",
  "common.delete": "Delete",
  "common.confirm.delete": "Confirm Delete",
  "common.delete.user": "Delete User",
  "common.error": "Error",
  "common.login": "Log In",
  "common.logout": "Log Out",
  "common.add": "Add",
  "common.remove": "Remove",
  "assigned.classes": "Assigned Classes",
  "dashboard.title": "Crew Progress Dashboard",
  "please.login": "Please click below to Login",
  "nav.more": "More",
  "nav.admin": "Admin",
  "nav.safety": "Safety",
  "nav.troubleshooting": "Troubleshooting",
  "nav.mob.inspection.checklist": "MOB Inspection Checklist",
  "nav.mob.drill.log": "MOB Drill Log",
  "nav.certification": "Certification",
  "only.change.needed":
    "Only change what is needed, rest of the values will remain.",
  "info.missing": "info missing",
  "select.user.editing": "Please select a user to begin editing",
  "serial.number.section.header": "Product Serial Numbers",
  "serial.number.table.header": "Serial Number",
  "serial.number.actions": "Actions",
  "sms.consent":
    "I consent to receive SMS verification codes from Twilio for logging into c-herotraining.com",
  "rescueDavitMount.title": "Rescue Davit Mounting",
  "rescueDavitMount.description":
    "The Davits can be mounted in 2 ways. Choose ONE of the following mounts:",
  "rescueDavit.title": "Rescue Davits",
  "rescueDavit.description":
    "The 4 Davit types differ in how the winch plate is attached to the davit base. Choose ONE of the following Rescue Davits:",
  "rescuePole.title": "Rescue Poles",
  "rescuePole.description":
    "Our 4 Rescue Poles differ in how the strap is attached to the Hoop. Choose ONE of the following Rescue Poles:",
};
